### ISSUE TITLE
Generate a proof of adjunction

### ISSUE THREAD

**Issue by tlringer** [uwplse/ornamental-search#57]
See  #39

**Comment by tlringer** [comment]
Useful: https://github.com/CoqHott/univalent_parametricity/blob/master/theories/HoTT.v

**Comment by tlringer** [comment]
This should quantify over all section/retraction proofs

**Comment by tlringer** [comment]
We can use this: https://github.com/jashug/IWTypes/blob/master/Adjointification.v

**Comment by nateyazdani** [comment]
Resolved by #68.
